sensors_info:
  - sensor:
      id: 11
      name: 'Rotation Vector'
      desc:

  - sensor:
      id: 1
      name: 'Reporting Mode On Change'
      desc: 'Events are reported only when the value changes.'

  - sensor:
      id: 35
      name: 'Accelerometer Uncalibrated'
      desc:

  - sensor:
      id: 4
      name: 'Gyroscope'
      desc:

  - sensor:
      id: 16
      name: 'Gyroscope Uncalibrated'
      desc: 'Similar to TYPE_GYROSCOPE but no gyro-drift compensation has been
      performed to adjust the given sensor values.'

  - sensor:
      id: 65536
      name: 'Type Device Private Base'
      desc:

  - sensor:
      id: 2
      name: 'Reporting Mode One Shot'
      desc:

  - sensor:
      id: 14
      name: 'Magnetic Field Uncalibrated'
      desc:

  - sensor:
      id: 3
      name: 'Orientation'
      desc:

  - sensor:
      id: 9
      name: 'Gravity'
      desc:

  - sensor:
      id: 20
      name: 'Geomagnetic Rotation Vector'
      desc: 'Similar to TYPE_ROTATION_VECTOR, but using a magnetometer
      instead of
      using a gyroscope. This sensor uses lower power than the other rotation
      vectors, because it does not use the gyroscope. However, it is more noisy
      and will work best outdoors.'

  - sensor:
        id: 10
        name: 'Linear Acceleration'
        desc:

  - sensor:
        id: 15
        name: 'Game Rotation Vector'
        desc: 'This an uncalibrated rotation vector sensor.'

  - sensor:
        id: 6
        name: 'Pressure'
        desc:

  - sensor:
        id: 18
        name: 'Step Detector'
        desc: 'A sensor of this type triggers an event each time a step is taken
        by the user. The only allowed value to return is 1.0 and an event is
        generated for each step. Like with any other event, the timestamp
        indicates when the event (here the step) occurred, this corresponds to
        when the foot hit the ground, generating a high variation in acceleration.
        This sensor is only for detecting every individual step as soon as it is
        taken, for example to perform dead reckoning.'

  - sensor:
        id: 19
        name: 'Step Counter'
        desc: 'A sensor of this type returns the number of steps taken by the
          user since the last reboot while activated. The value is returned
          as a float (with the fractional part set to zero) and is reset to
          zero only on a
        system reboot. The timestamp of the event is set to the time when the last
        step for that event was taken. This sensor is implemented in hardware and
        is expected to be low power. If you want to continuously track the number
        of steps over a long period of time, do NOT unregister for this sensor,
        so that it keeps counting steps in the background even when the AP is in
        suspend mode and report the aggregate count when the AP is awake.
        Application needs to stay registered for this sensor because step counter
        does not count steps if it is not activated. This sensor is ideal for
        fitness tracking applications.'

  - sensor:
        id: 5
        name: 'Light'
        desc:
  - sensor:
        id: 8
        name: 'Proximity'
        desc:
  - sensor:
        id: 27
        name: 'Unknown Sensor'
        desc:

  - sensor:
        id: 22
        name: 'Unknown Sensor_1'
        desc: