#####
#contents:
#  - raw_data: 'F:/raw_data/raw_data' : This is the raw path folder where all
#                  persons data should exists.
#  - output_path: 'F:/bawml/output' : Specify a directory where all data will
#                 be saved. e.g series,spectrogram's,training
#  - test_name: 'schokolade' : Any arbitrary name which will be used to
#               create sub directory.

#####
contents:
  raw_data: ''
  output_path: ''
  test_name: ''